<?php
/**
 * ServiceAvailabilityFormat
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\Shipping\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Royal Mail API Shipping V3 (REST)
 *
 * API Shipping V3 (REST) provides the functionality for customers to take a shipping transaction from creation to collection.   It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.  Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic and international items with Royal Mail.  Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers??? own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.  This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.
 *
 * OpenAPI spec version: 3.0.20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMail\Shipping\Rest\Api\models;

use \ArrayAccess;
use \RoyalMail\Shipping\Rest\Api\ObjectSerializer;

/**
 * ServiceAvailabilityFormat Class Doc Comment
 *
 * @category Class
 * @description Available Format for a service, with the maximum possible weight allowed.
 * @package  RoyalMail\Shipping\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServiceAvailabilityFormat implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ServiceAvailability.Format';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'serviceFormat' => 'string',
'formatDescription' => 'string',
'maxWeight' => 'double'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'serviceFormat' => null,
'formatDescription' => null,
'maxWeight' => 'double'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'serviceFormat' => 'ServiceFormat',
'formatDescription' => 'FormatDescription',
'maxWeight' => 'MaxWeight'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'serviceFormat' => 'setServiceFormat',
'formatDescription' => 'setFormatDescription',
'maxWeight' => 'setMaxWeight'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'serviceFormat' => 'getServiceFormat',
'formatDescription' => 'getFormatDescription',
'maxWeight' => 'getMaxWeight'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const SERVICE_FORMAT_L = 'L';
const SERVICE_FORMAT_F = 'F';
const SERVICE_FORMAT_P = 'P';
const SERVICE_FORMAT_S = 'S';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getServiceFormatAllowableValues()
    {
        return [
            self::SERVICE_FORMAT_L,
self::SERVICE_FORMAT_F,
self::SERVICE_FORMAT_P,
self::SERVICE_FORMAT_S,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['serviceFormat'] = isset($data['serviceFormat']) ? $data['serviceFormat'] : null;
        $this->container['formatDescription'] = isset($data['formatDescription']) ? $data['formatDescription'] : null;
        $this->container['maxWeight'] = isset($data['maxWeight']) ? $data['maxWeight'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getServiceFormatAllowableValues();
        if (!is_null($this->container['serviceFormat']) && !in_array($this->container['serviceFormat'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'serviceFormat', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['formatDescription'] === null) {
            $invalidProperties[] = "'formatDescription' can't be null";
        }
        if ($this->container['maxWeight'] === null) {
            $invalidProperties[] = "'maxWeight' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets serviceFormat
     *
     * @return string
     */
    public function getServiceFormat()
    {
        return $this->container['serviceFormat'];
    }

    /**
     * Sets serviceFormat
     *
     * @param string $serviceFormat Service Format<br />An available service format for this service.<br />If blank, then formats are not applicable for this service.<br />            <br />**L** - Letter<br />**F** - Large Letter<br />**P** - Parcel<br />**S** - Printed Papers<br />**Blank** - Not Applicable
     *
     * @return $this
     */
    public function setServiceFormat($serviceFormat)
    {
        $allowedValues = $this->getServiceFormatAllowableValues();
        if (!is_null($serviceFormat) && !in_array($serviceFormat, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'serviceFormat', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['serviceFormat'] = $serviceFormat;

        return $this;
    }

    /**
     * Gets formatDescription
     *
     * @return string
     */
    public function getFormatDescription()
    {
        return $this->container['formatDescription'];
    }

    /**
     * Sets formatDescription
     *
     * @param string $formatDescription Format Description<br />A description of the Service Format<br />            <br />Letter<br />Large Letter<br />Parcel<br />International Printed Papaers<br />Not Applicable
     *
     * @return $this
     */
    public function setFormatDescription($formatDescription)
    {
        $this->container['formatDescription'] = $formatDescription;

        return $this;
    }

    /**
     * Gets maxWeight
     *
     * @return double
     */
    public function getMaxWeight()
    {
        return $this->container['maxWeight'];
    }

    /**
     * Sets maxWeight
     *
     * @param double $maxWeight Maximum Weight<br />The maximum weight allowed for this format (or service if formats not applicable) in specified Unit of Measure.
     *
     * @return $this
     */
    public function setMaxWeight($maxWeight)
    {
        $this->container['maxWeight'] = $maxWeight;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
