<?php
/**
 * ServiceAvailabilityOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\Shipping\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Royal Mail API Shipping V3 (REST)
 *
 * This API specification details the requirements for integrating with **Royal Mail API Shipping V3**.<br><br>It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.<br><br>Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic items with Royal Mail.<br><br>Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming and offline barcoding to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers’ own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.<br><br>This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.
 *
 * OpenAPI spec version: 3.0.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMail\Shipping\Rest\Api\models;

use \ArrayAccess;
use \RoyalMail\Shipping\Rest\Api\ObjectSerializer;

/**
 * ServiceAvailabilityOption Class Doc Comment
 *
 * @category Class
 * @description An available service option based on your request.
 * @package  RoyalMail\Shipping\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServiceAvailabilityOption implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ServiceAvailability.Option';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'serviceCode' => 'string',
'serviceName' => 'string',
'transitDays' => 'int',
'isTracked' => 'bool',
'signatureIncluded' => 'bool',
'recordedSignedForAvailable' => 'bool',
'safeplaceAvailable' => 'bool',
'localCollectAvailable' => 'bool',
'saturdayGuaranteedAvailable' => 'bool',
'consequentialLossAvailable' => 'bool',
'formatsAvailable' => '\RoyalMail\Shipping\Rest\Api\models\ServiceAvailabilityFormat[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'serviceCode' => null,
'serviceName' => null,
'transitDays' => 'int32',
'isTracked' => null,
'signatureIncluded' => null,
'recordedSignedForAvailable' => null,
'safeplaceAvailable' => null,
'localCollectAvailable' => null,
'saturdayGuaranteedAvailable' => null,
'consequentialLossAvailable' => null,
'formatsAvailable' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'serviceCode' => 'ServiceCode',
'serviceName' => 'ServiceName',
'transitDays' => 'TransitDays',
'isTracked' => 'IsTracked',
'signatureIncluded' => 'SignatureIncluded',
'recordedSignedForAvailable' => 'RecordedSignedForAvailable',
'safeplaceAvailable' => 'SafeplaceAvailable',
'localCollectAvailable' => 'LocalCollectAvailable',
'saturdayGuaranteedAvailable' => 'SaturdayGuaranteedAvailable',
'consequentialLossAvailable' => 'ConsequentialLossAvailable',
'formatsAvailable' => 'FormatsAvailable'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'serviceCode' => 'setServiceCode',
'serviceName' => 'setServiceName',
'transitDays' => 'setTransitDays',
'isTracked' => 'setIsTracked',
'signatureIncluded' => 'setSignatureIncluded',
'recordedSignedForAvailable' => 'setRecordedSignedForAvailable',
'safeplaceAvailable' => 'setSafeplaceAvailable',
'localCollectAvailable' => 'setLocalCollectAvailable',
'saturdayGuaranteedAvailable' => 'setSaturdayGuaranteedAvailable',
'consequentialLossAvailable' => 'setConsequentialLossAvailable',
'formatsAvailable' => 'setFormatsAvailable'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'serviceCode' => 'getServiceCode',
'serviceName' => 'getServiceName',
'transitDays' => 'getTransitDays',
'isTracked' => 'getIsTracked',
'signatureIncluded' => 'getSignatureIncluded',
'recordedSignedForAvailable' => 'getRecordedSignedForAvailable',
'safeplaceAvailable' => 'getSafeplaceAvailable',
'localCollectAvailable' => 'getLocalCollectAvailable',
'saturdayGuaranteedAvailable' => 'getSaturdayGuaranteedAvailable',
'consequentialLossAvailable' => 'getConsequentialLossAvailable',
'formatsAvailable' => 'getFormatsAvailable'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['serviceCode'] = isset($data['serviceCode']) ? $data['serviceCode'] : null;
        $this->container['serviceName'] = isset($data['serviceName']) ? $data['serviceName'] : null;
        $this->container['transitDays'] = isset($data['transitDays']) ? $data['transitDays'] : null;
        $this->container['isTracked'] = isset($data['isTracked']) ? $data['isTracked'] : null;
        $this->container['signatureIncluded'] = isset($data['signatureIncluded']) ? $data['signatureIncluded'] : null;
        $this->container['recordedSignedForAvailable'] = isset($data['recordedSignedForAvailable']) ? $data['recordedSignedForAvailable'] : null;
        $this->container['safeplaceAvailable'] = isset($data['safeplaceAvailable']) ? $data['safeplaceAvailable'] : null;
        $this->container['localCollectAvailable'] = isset($data['localCollectAvailable']) ? $data['localCollectAvailable'] : null;
        $this->container['saturdayGuaranteedAvailable'] = isset($data['saturdayGuaranteedAvailable']) ? $data['saturdayGuaranteedAvailable'] : null;
        $this->container['consequentialLossAvailable'] = isset($data['consequentialLossAvailable']) ? $data['consequentialLossAvailable'] : null;
        $this->container['formatsAvailable'] = isset($data['formatsAvailable']) ? $data['formatsAvailable'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['serviceCode'] === null) {
            $invalidProperties[] = "'serviceCode' can't be null";
        }
        if ($this->container['serviceName'] === null) {
            $invalidProperties[] = "'serviceName' can't be null";
        }
        if ($this->container['transitDays'] === null) {
            $invalidProperties[] = "'transitDays' can't be null";
        }
        if ($this->container['isTracked'] === null) {
            $invalidProperties[] = "'isTracked' can't be null";
        }
        if ($this->container['signatureIncluded'] === null) {
            $invalidProperties[] = "'signatureIncluded' can't be null";
        }
        if ($this->container['recordedSignedForAvailable'] === null) {
            $invalidProperties[] = "'recordedSignedForAvailable' can't be null";
        }
        if ($this->container['safeplaceAvailable'] === null) {
            $invalidProperties[] = "'safeplaceAvailable' can't be null";
        }
        if ($this->container['localCollectAvailable'] === null) {
            $invalidProperties[] = "'localCollectAvailable' can't be null";
        }
        if ($this->container['saturdayGuaranteedAvailable'] === null) {
            $invalidProperties[] = "'saturdayGuaranteedAvailable' can't be null";
        }
        if ($this->container['consequentialLossAvailable'] === null) {
            $invalidProperties[] = "'consequentialLossAvailable' can't be null";
        }
        if ($this->container['formatsAvailable'] === null) {
            $invalidProperties[] = "'formatsAvailable' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets serviceCode
     *
     * @return string
     */
    public function getServiceCode()
    {
        return $this->container['serviceCode'];
    }

    /**
     * Sets serviceCode
     *
     * @param string $serviceCode Service Code<br />Customer Mapped Service Code or System Service Code for this service.
     *
     * @return $this
     */
    public function setServiceCode($serviceCode)
    {
        $this->container['serviceCode'] = $serviceCode;

        return $this;
    }

    /**
     * Gets serviceName
     *
     * @return string
     */
    public function getServiceName()
    {
        return $this->container['serviceName'];
    }

    /**
     * Sets serviceName
     *
     * @param string $serviceName Service Name
     *
     * @return $this
     */
    public function setServiceName($serviceName)
    {
        $this->container['serviceName'] = $serviceName;

        return $this;
    }

    /**
     * Gets transitDays
     *
     * @return int
     */
    public function getTransitDays()
    {
        return $this->container['transitDays'];
    }

    /**
     * Sets transitDays
     *
     * @param int $transitDays Estimated Transit Days
     *
     * @return $this
     */
    public function setTransitDays($transitDays)
    {
        $this->container['transitDays'] = $transitDays;

        return $this;
    }

    /**
     * Gets isTracked
     *
     * @return bool
     */
    public function getIsTracked()
    {
        return $this->container['isTracked'];
    }

    /**
     * Sets isTracked
     *
     * @param bool $isTracked Is Tracked<br />If true, the service is a tracked service.
     *
     * @return $this
     */
    public function setIsTracked($isTracked)
    {
        $this->container['isTracked'] = $isTracked;

        return $this;
    }

    /**
     * Gets signatureIncluded
     *
     * @return bool
     */
    public function getSignatureIncluded()
    {
        return $this->container['signatureIncluded'];
    }

    /**
     * Sets signatureIncluded
     *
     * @param bool $signatureIncluded Signature Included<br />If true, a signature required on delivery is included with the service.
     *
     * @return $this
     */
    public function setSignatureIncluded($signatureIncluded)
    {
        $this->container['signatureIncluded'] = $signatureIncluded;

        return $this;
    }

    /**
     * Gets recordedSignedForAvailable
     *
     * @return bool
     */
    public function getRecordedSignedForAvailable()
    {
        return $this->container['recordedSignedForAvailable'];
    }

    /**
     * Sets recordedSignedForAvailable
     *
     * @param bool $recordedSignedForAvailable Recorded Signed For Enhancement Available<br />If true, the recorded signed for enhancement can be used with this service.
     *
     * @return $this
     */
    public function setRecordedSignedForAvailable($recordedSignedForAvailable)
    {
        $this->container['recordedSignedForAvailable'] = $recordedSignedForAvailable;

        return $this;
    }

    /**
     * Gets safeplaceAvailable
     *
     * @return bool
     */
    public function getSafeplaceAvailable()
    {
        return $this->container['safeplaceAvailable'];
    }

    /**
     * Sets safeplaceAvailable
     *
     * @param bool $safeplaceAvailable Safe Place Enhancement Available<br />If true, the safe place enhancement can be used with this service.
     *
     * @return $this
     */
    public function setSafeplaceAvailable($safeplaceAvailable)
    {
        $this->container['safeplaceAvailable'] = $safeplaceAvailable;

        return $this;
    }

    /**
     * Gets localCollectAvailable
     *
     * @return bool
     */
    public function getLocalCollectAvailable()
    {
        return $this->container['localCollectAvailable'];
    }

    /**
     * Sets localCollectAvailable
     *
     * @param bool $localCollectAvailable Local Collect Enhancement Available<br />If true, the local collect enhancement can be used with this service.
     *
     * @return $this
     */
    public function setLocalCollectAvailable($localCollectAvailable)
    {
        $this->container['localCollectAvailable'] = $localCollectAvailable;

        return $this;
    }

    /**
     * Gets saturdayGuaranteedAvailable
     *
     * @return bool
     */
    public function getSaturdayGuaranteedAvailable()
    {
        return $this->container['saturdayGuaranteedAvailable'];
    }

    /**
     * Sets saturdayGuaranteedAvailable
     *
     * @param bool $saturdayGuaranteedAvailable Saturday Guaranteed Enhancement Available<br />If true, the saturday guaranteed enhancement can be used with this service.
     *
     * @return $this
     */
    public function setSaturdayGuaranteedAvailable($saturdayGuaranteedAvailable)
    {
        $this->container['saturdayGuaranteedAvailable'] = $saturdayGuaranteedAvailable;

        return $this;
    }

    /**
     * Gets consequentialLossAvailable
     *
     * @return bool
     */
    public function getConsequentialLossAvailable()
    {
        return $this->container['consequentialLossAvailable'];
    }

    /**
     * Sets consequentialLossAvailable
     *
     * @param bool $consequentialLossAvailable Consequential Loss Enhancement Available<br />If true, the consequential loss enhancement can be used with this service.
     *
     * @return $this
     */
    public function setConsequentialLossAvailable($consequentialLossAvailable)
    {
        $this->container['consequentialLossAvailable'] = $consequentialLossAvailable;

        return $this;
    }

    /**
     * Gets formatsAvailable
     *
     * @return \RoyalMail\Shipping\Rest\Api\models\ServiceAvailabilityFormat[]
     */
    public function getFormatsAvailable()
    {
        return $this->container['formatsAvailable'];
    }

    /**
     * Sets formatsAvailable
     *
     * @param \RoyalMail\Shipping\Rest\Api\models\ServiceAvailabilityFormat[] $formatsAvailable Formats Available<br />All formats that are available for this service for the given weight, including the maximum weight possible for each format.
     *
     * @return $this
     */
    public function setFormatsAvailable($formatsAvailable)
    {
        $this->container['formatsAvailable'] = $formatsAvailable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
