<?php
/**
 * ServiceAvailabilityServiceOptions
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\Shipping\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Royal Mail API Shipping V3 (REST)
 *
 * API Shipping V3 (REST) provides the functionality for customers to take a shipping transaction from creation to collection.   It specifically covers how the Royal Mail API Shipping V3 can be used by business customers to conduct shipping activity with Royal Mail and provides the technical information to build this integration. This specification must be used with the relevant accompanying specifications for customers wishing to interface their systems with Royal Mail services.  Royal Mail API Shipping V3 exposes a fully RESTful service that allows account customers to create shipments, produce labels, and produce documentation for all the tasks required to ship domestic and international items with Royal Mail.  Built on industry standards, Royal Mail API Shipping V3 provides a simple and low cost method for customers to integrate with Royal Mail, and allows them to get shipping quickly. The API offers data streaming to allow customers greater flexibility when generating their labels. There are no costs to customers for using the Royal Mail API Shipping V3 services, however customers??? own development costs must be covered by the customer developing the solution. Royal Mail will not accept any responsibility for these development, implementation and testing costs. Customers should address initial enquiries regarding development of systems for these purposes to their account handler.  This API can be used in conjunction with Royal Mail Pro Shipping, a GUI based shipping platform. For more details on Royal Mail Pro Shipping, including videos on and briefs on updating/ cancelling a shipment and Manifesting please refer to http://www.royalmail.com/pro-shipping-help.
 *
 * OpenAPI spec version: 3.0.20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMail\Shipping\Rest\Api\models;

use \ArrayAccess;
use \RoyalMail\Shipping\Rest\Api\ObjectSerializer;

/**
 * ServiceAvailabilityServiceOptions Class Doc Comment
 *
 * @category Class
 * @description Service Options&lt;br /&gt;Specify any service requirements such as format required or enhancements required.
 * @package  RoyalMail\Shipping\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServiceAvailabilityServiceOptions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ServiceAvailability.ServiceOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'serviceFormat' => 'string',
'tracked' => 'bool',
'signatureRequired' => 'bool',
'safeplace' => 'bool',
'localCollect' => 'bool',
'saturdayGuaranteed' => 'bool',
'consequentialLoss' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'serviceFormat' => null,
'tracked' => null,
'signatureRequired' => null,
'safeplace' => null,
'localCollect' => null,
'saturdayGuaranteed' => null,
'consequentialLoss' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'serviceFormat' => 'ServiceFormat',
'tracked' => 'Tracked',
'signatureRequired' => 'SignatureRequired',
'safeplace' => 'Safeplace',
'localCollect' => 'LocalCollect',
'saturdayGuaranteed' => 'SaturdayGuaranteed',
'consequentialLoss' => 'ConsequentialLoss'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'serviceFormat' => 'setServiceFormat',
'tracked' => 'setTracked',
'signatureRequired' => 'setSignatureRequired',
'safeplace' => 'setSafeplace',
'localCollect' => 'setLocalCollect',
'saturdayGuaranteed' => 'setSaturdayGuaranteed',
'consequentialLoss' => 'setConsequentialLoss'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'serviceFormat' => 'getServiceFormat',
'tracked' => 'getTracked',
'signatureRequired' => 'getSignatureRequired',
'safeplace' => 'getSafeplace',
'localCollect' => 'getLocalCollect',
'saturdayGuaranteed' => 'getSaturdayGuaranteed',
'consequentialLoss' => 'getConsequentialLoss'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const SERVICE_FORMAT_L = 'L';
const SERVICE_FORMAT_F = 'F';
const SERVICE_FORMAT_P = 'P';
const SERVICE_FORMAT_S = 'S';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getServiceFormatAllowableValues()
    {
        return [
            self::SERVICE_FORMAT_L,
self::SERVICE_FORMAT_F,
self::SERVICE_FORMAT_P,
self::SERVICE_FORMAT_S,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['serviceFormat'] = isset($data['serviceFormat']) ? $data['serviceFormat'] : null;
        $this->container['tracked'] = isset($data['tracked']) ? $data['tracked'] : null;
        $this->container['signatureRequired'] = isset($data['signatureRequired']) ? $data['signatureRequired'] : null;
        $this->container['safeplace'] = isset($data['safeplace']) ? $data['safeplace'] : null;
        $this->container['localCollect'] = isset($data['localCollect']) ? $data['localCollect'] : null;
        $this->container['saturdayGuaranteed'] = isset($data['saturdayGuaranteed']) ? $data['saturdayGuaranteed'] : null;
        $this->container['consequentialLoss'] = isset($data['consequentialLoss']) ? $data['consequentialLoss'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getServiceFormatAllowableValues();
        if (!is_null($this->container['serviceFormat']) && !in_array($this->container['serviceFormat'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'serviceFormat', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets serviceFormat
     *
     * @return string
     */
    public function getServiceFormat()
    {
        return $this->container['serviceFormat'];
    }

    /**
     * Sets serviceFormat
     *
     * @param string $serviceFormat Service Format<br />If provided, only return services that support the given service format.<br />            <br />**L** - Letter<br />**F** - Large Letter<br />**P** - Parcel<br />**S** - Printed Papers - International Services Only
     *
     * @return $this
     */
    public function setServiceFormat($serviceFormat)
    {
        $allowedValues = $this->getServiceFormatAllowableValues();
        if (!is_null($serviceFormat) && !in_array($serviceFormat, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'serviceFormat', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['serviceFormat'] = $serviceFormat;

        return $this;
    }

    /**
     * Gets tracked
     *
     * @return bool
     */
    public function getTracked()
    {
        return $this->container['tracked'];
    }

    /**
     * Sets tracked
     *
     * @param bool $tracked Tracked Services<br />If true, only return Tracked Services.
     *
     * @return $this
     */
    public function setTracked($tracked)
    {
        $this->container['tracked'] = $tracked;

        return $this;
    }

    /**
     * Gets signatureRequired
     *
     * @return bool
     */
    public function getSignatureRequired()
    {
        return $this->container['signatureRequired'];
    }

    /**
     * Sets signatureRequired
     *
     * @param bool $signatureRequired Signature Required<br />If true, only return services that are either with signature or support the Recorded Signed For enhancement.
     *
     * @return $this
     */
    public function setSignatureRequired($signatureRequired)
    {
        $this->container['signatureRequired'] = $signatureRequired;

        return $this;
    }

    /**
     * Gets safeplace
     *
     * @return bool
     */
    public function getSafeplace()
    {
        return $this->container['safeplace'];
    }

    /**
     * Sets safeplace
     *
     * @param bool $safeplace Safe Place Enhancement<br />If true, only return services that support the Safe Place enhancement.
     *
     * @return $this
     */
    public function setSafeplace($safeplace)
    {
        $this->container['safeplace'] = $safeplace;

        return $this;
    }

    /**
     * Gets localCollect
     *
     * @return bool
     */
    public function getLocalCollect()
    {
        return $this->container['localCollect'];
    }

    /**
     * Sets localCollect
     *
     * @param bool $localCollect Local Collect Enhancement<br />If true, only return services that support the Local Collect enhancement.
     *
     * @return $this
     */
    public function setLocalCollect($localCollect)
    {
        $this->container['localCollect'] = $localCollect;

        return $this;
    }

    /**
     * Gets saturdayGuaranteed
     *
     * @return bool
     */
    public function getSaturdayGuaranteed()
    {
        return $this->container['saturdayGuaranteed'];
    }

    /**
     * Sets saturdayGuaranteed
     *
     * @param bool $saturdayGuaranteed Saturday Guaranteed Enhancement<br />If true, only return services that support the Saturday Guaranteed enhancement.
     *
     * @return $this
     */
    public function setSaturdayGuaranteed($saturdayGuaranteed)
    {
        $this->container['saturdayGuaranteed'] = $saturdayGuaranteed;

        return $this;
    }

    /**
     * Gets consequentialLoss
     *
     * @return bool
     */
    public function getConsequentialLoss()
    {
        return $this->container['consequentialLoss'];
    }

    /**
     * Sets consequentialLoss
     *
     * @param bool $consequentialLoss Consequential Loss Enhancement<br />If true, only return services that support the Consequential Loss enhancement.
     *
     * @return $this
     */
    public function setConsequentialLoss($consequentialLoss)
    {
        $this->container['consequentialLoss'] = $consequentialLoss;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
